name: Infections
main: io.github.jisaacs1207.infections.Infections
version: 1.0
author: jisaacs1207
website: http://fivekingdoms.net
description: >
             Fight off or give yourself over to an infection!

commands:
   infect:
      aliases: [infections, infection, inf]
      description: Infection information.
   enthrall:
      description: Enthralls a target.
   dethrall:
      description: Releases your thrall.